# -*- coding: utf-8 -*-
"""Fund.Bio

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ifLZh-Avus_WmgqDTR_AFWX1rw7M_qm6
"""

from tkinter import ttk
from tkinter import *

import sqlite3

class BILINION:
   def __init__(self,root):
     self.wind = root
     self.wind.title("BILINION")
     self.wind.geometry("250x320")
       
     frame1 = LabelFrame(self.wind, text="Nivel aproximado de bilirrubina", font=("calibri",14))
     frame2 = LabelFrame(self.wind, text="Nivel de ictericia", font=("calibri",14))
        
     frame1.pack(fill="both",expand="yes",padx=5,pady=5)
     frame2.pack(fill="both",expand="yes",padx=5,pady=5)
        
     self.trv = ttk.Treeview(frame1, columns=(1,2),show="headings",height="2")
     self.trv.pack()

     self.trv.heading(1, text="Resultado 1")
     self.trv.heading(2, text="unidades")

     self.trv = ttk.Treeview(frame2, columns=(1,2),show="headings",height="2")
     self.trv.pack()

     self.trv.heading(1, text="Resultado 2")
     self.trv.heading(2, text="unidades")
 
     btn1 = Button(frame1, text="Repetir", width=12, height=2)
     btn1.grid(row=5, column=0)

     btn2 = Button(frame1, text="Finalizar", width=12, height=2)
     btn2.grid(row=5, column=1)

if __name__ == '__main__' :
    root = Tk()
    product = BILINION(root)
    root.mainloop()
